const sidebar = {
    '/base/components/': [
        '1.index',
        '1.legend',
        '2.grid',
        '2.polar',
        '2.radiusAxis',
        '2.xAxis',
        '2.yAxis',
        '3.angleAxis',
        '4.radar',
        '5.dataZoom',
        '6.visualMap',
        '7.tooltip',
        '8.geo',
    ],
    '/base/series/': [
        '1.index',
        '1.line',
        '2.bar',
        '3.pie',
        '4.scatter',
        '5.effectScatter',
        '6.radar',
        '7.tree',
        '8.treemap',
        '9.sunburst',
        '10.boxplot',
        '11.candlestick',
        '12.heatmap',
        '13.map',
        '14.parallel',
        '15.lines',
        '16.graph',
        '17.sankey',
        '18.funnel',
        '19.gauge',
        '20.pictorialBar',
        '21.themeRiver',
        '22.custom',
    ],
    '/base/api/': [
        '1.index',
        '1.echarts',
        '2.echartsInstance',
        '3.action',
        '4.events'
    ],
    '/base/gl/': [
        '1.index',
        '1.scatter3D',
        '2.bar3D',
        '3.line3D',
        '4.lines3D',
        '5.map3D',
        '6.surface',
        '7.polygons3D',
        '8.scatterGL',
        '9.graphGL',
        '10.flowGL'
    ],
    '/senior/1.micro/': [
        '1.index',
        '1.singlespa',
        '1.singlespa2',
        '2.qiankun',
        '2.qiankun2',
        '3.share',
        '4.dev'
    ],
    '/senior/2.typescript/': [
        '1.index',
        '1.env',
        '2.base',
        '3.deduction',
        '4.type',
        '5.class',
        '6.interface',
        '7.generic',
        '8.compatible',
        '9.protect',
        '10.infer',
        '11.overlapping',
        '12.condition',
        '13.builtin',
        '14.package',
        '15.custom',
        '16.unknown',
        '17.module',
        '18.statement',
        '19.extend'
    ],
    '/senior/3.deploy/': [
        '1.index',
        '1.local',
        '2.gitlab',
        '3.genkins',
        '4.centos',
        '5.nginx'
    ],
    '/senior/4.component/': [
        '1.index',
        '1.button',
        '2.dropdown',
        '3.form',
        '4.input',
        '5.checkBox',
        '6.cascader',
        '7.date',
        '8.dispaly',
        '9.dynamics',
        '1.env',
        '10.tree',
        '12.table',
        '1.recursion',
        '3.dialog',
        '4.render',
        '9.alert',
        '13.publish',
    ],
    '/senior/vue3/': [
        '1.index',
    ],
    // '/source/vue-cli2.x/': [
    //     '1.index'
    // ],
    // '/source/vue2.x/': [
    //     '1.index',
    //     '2.initGlobalAPI',
    //     '3.initMixin',
    //     '4.stateMixin',
    //     '5.eventsMixin',
    //     '6.lifecycleMixin',
    //     '7.renderMixin',
    //     '8.mount',
    //     '9.ast',
    //     '10.optimize',
    //     '11.gencode',
    //     '12.mount',
    //     '13._render',
    //     '14._update'
    // ],
    // '/source/vue-router3.x/': [
    //     '1.index',
    //     '2.origin'
    // ],
    // '/source/vuex3.x/': [
    //     '1.index',
    //     '2.use',
    //     '3.origin'
    // ],
    // '/source/vue-cli3.x/': [
    //     '1.index',
    // ],
    // '/source/vue3.x/': [
    //     '1.index',
    //     '2.initGlobalAPI',
    //     '3.initMixin',
    //     '4.stateMixin',
    //     '5.eventsMixin',
    //     '6.lifecycleMixin',
    //     '7.renderMixin',
    //     '8.mount',
    //     '9.ast',
    //     '10.optimize',
    //     '11.gencode',
    //     '12.mount',
    //     '13._render',
    //     '14._update'
    // ],
    // '/source/vue-router4.x/': [
    //     '1.index'
    // ],
    // '/source/vuex4.x/': [
    //     '1.index'
    // ]
}
module.exports = sidebar